version: '3'

services:
  api:
    build:
      context: ./apps/api
    container_name: dash-skin-challenger_api
    command: sh -c "yarn install && yarn seed:run && yarn start:dev"
    ports:
      - '3333:3333'
    depends_on:
      - mongodb
    links:
      - mongodb
    environment:
      NODE_ENV: development
      DATABASE_URL: 'mongodb://mongodb:27017/dashskins'
      JWT_KEY: "OC9r/g6my20R/UQfCr5RJlc6nFW49C/txlqz8IIx39Q="
      SESSION_EXPIRES: 3600

  web:
    build:
      context: ./apps/web
    container_name: dash-skin-challenger_web
    command: sh -c "yarn install && yarn dev --host"
    ports:
      - '5173:5173'
    links:
      - api
    environment:
      VITE_API_URL: http://localhost:3333

  mongodb:
    image: mongo
    container_name: dash-skin-challenger_db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=dashskins
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: