version: '3'

services:
  mongodb:
    image: mongo
    container_name: dash-skin-challenger_db
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=dashskins
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: